// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	models "CartridgeServer/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// Reader is an autogenerated mock type for the Reader type
type Reader struct {
	mock.Mock
}

type Reader_Expecter struct {
	mock *mock.Mock
}

func (_m *Reader) EXPECT() *Reader_Expecter {
	return &Reader_Expecter{mock: &_m.Mock}
}

// ReadCartridges provides a mock function with given fields: offset, limit, name
func (_m *Reader) ReadCartridges(offset int, limit int, name string) ([]models.CartridgeModel, error) {
	ret := _m.Called(offset, limit, name)

	if len(ret) == 0 {
		panic("no return value specified for ReadCartridges")
	}

	var r0 []models.CartridgeModel
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int, string) ([]models.CartridgeModel, error)); ok {
		return rf(offset, limit, name)
	}
	if rf, ok := ret.Get(0).(func(int, int, string) []models.CartridgeModel); ok {
		r0 = rf(offset, limit, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.CartridgeModel)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, string) error); ok {
		r1 = rf(offset, limit, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Reader_ReadCartridges_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadCartridges'
type Reader_ReadCartridges_Call struct {
	*mock.Call
}

// ReadCartridges is a helper method to define mock.On call
//   - offset int
//   - limit int
//   - name string
func (_e *Reader_Expecter) ReadCartridges(offset interface{}, limit interface{}, name interface{}) *Reader_ReadCartridges_Call {
	return &Reader_ReadCartridges_Call{Call: _e.mock.On("ReadCartridges", offset, limit, name)}
}

func (_c *Reader_ReadCartridges_Call) Run(run func(offset int, limit int, name string)) *Reader_ReadCartridges_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int), args[2].(string))
	})
	return _c
}

func (_c *Reader_ReadCartridges_Call) Return(_a0 []models.CartridgeModel, _a1 error) *Reader_ReadCartridges_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Reader_ReadCartridges_Call) RunAndReturn(run func(int, int, string) ([]models.CartridgeModel, error)) *Reader_ReadCartridges_Call {
	_c.Call.Return(run)
	return _c
}

// NewReader creates a new instance of Reader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *Reader {
	mock := &Reader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
